services:
  - type: web
    name: nhyira-haven-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: nhyira-haven-db
          property: connectionString
      - key: Jwt__Key
        generateValue: true
      - key: Jwt__Issuer
        value: NhyiraHaven
      - key: Jwt__Audience
        value: NhyiraHaven

databases:
  - name: nhyira-haven-db
    plan: free